package ru.vaulttracker;

import com.google.gson.Gson;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.LongSupplier;
import java.util.logging.Logger;

/** Dedicated disk worker: region threads only enqueue immutable snapshots and presence changes. */
final class GuardService implements AutoCloseable {
    static final long RETENTION=30L*24*60*60*1000, CODE_TTL=10*60*1000L;
    record Account(UUID uuid,String name,boolean notifications) {}
    record Event(long id,long time,String name,String location,Map<String,Long> changes,boolean removed) {}
    record Delivery(long id,long recipient,String text) {}
    private record Code(long user,long expires) {}
    private final ScheduledExecutorService disk=Executors.newSingleThreadScheduledExecutor(r->new Thread(r,"VaultTracker-guard-disk"));
    private final Connection db;
    private final Logger log;
    private final LongSupplier clock;
    private final long started;
    private final Map<UUID,Long> presence=new ConcurrentHashMap<>(); // -1 online, otherwise exit timestamp
    private final Map<BlockKey,Snapshot> baseline=new ConcurrentHashMap<>();
    private final Map<String,Code> codes=new HashMap<>();
    private final SecureRandom random=new SecureRandom();
    private final Gson gson=new Gson();
    private volatile GuardConfig config;
    private volatile Set<Long> admins=Set.of();
    private long lastPrune;

    GuardService(Path path,GuardConfig config,Logger log) throws Exception { this(path,config,log,System::currentTimeMillis); }
    GuardService(Path path,GuardConfig config,Logger log,LongSupplier clock) throws Exception {
        this.config=config; this.log=log; this.clock=clock; started=clock.getAsLong();
        Class.forName("org.h2.Driver");
        db=DriverManager.getConnection("jdbc:h2:"+path.toAbsolutePath()+";DB_CLOSE_ON_EXIT=FALSE","sa","");
        try(var s=db.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS accounts (tg BIGINT PRIMARY KEY, uuid VARCHAR(36) UNIQUE NOT NULL, nickname VARCHAR(64) NOT NULL, alerts BOOLEAN NOT NULL DEFAULT TRUE)");
            s.execute("CREATE TABLE IF NOT EXISTS preferences (tg BIGINT PRIMARY KEY, alerts BOOLEAN NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS presence (uuid VARCHAR(36) PRIMARY KEY, departed BIGINT NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, happened BIGINT NOT NULL, payload CLOB NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS outbox (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id BIGINT, tg BIGINT NOT NULL, owner_uuid VARCHAR(36), body CLOB NOT NULL, due BIGINT NOT NULL, created BIGINT NOT NULL)");
            s.execute("CREATE INDEX IF NOT EXISTS guard_event_time ON events(happened)");
            s.execute("CREATE INDEX IF NOT EXISTS guard_outbox_due ON outbox(due)");
        }
        try(var s=db.createStatement();var rs=s.executeQuery("SELECT uuid, departed FROM presence")) {
            while(rs.next()) presence.put(UUID.fromString(rs.getString(1)),rs.getLong(2)<0 ? started : rs.getLong(2));
        }
        execute("UPDATE presence SET departed=? WHERE departed<0",started);
        disk.scheduleWithFixedDelay(()-> {try {prune();} catch(Exception e) {log.warning("Не удалось очистить историю охраны.");}},1,60,TimeUnit.MINUTES);
    }
    void configure(GuardConfig config,Set<Long> admins) { this.config=config; this.admins=Set.copyOf(admins); }
    boolean admin(long user) { return admins.contains(user); }
    boolean enabled() { return config.enabled(); }
    void restore(Collection<Snapshot> snapshots) {for(var v:snapshots) if(v.active()) baseline.put(v.sign(),v);}
    void presence(UUID uuid,String name,boolean online) {
        long time=online ? -1 : clock.getAsLong(); presence.put(uuid,time);
        enqueue(()-> {
            execute("MERGE INTO presence KEY(uuid) VALUES(?,?)",uuid.toString(),time);
            if(online) execute("UPDATE accounts SET nickname=? WHERE uuid=?",name,uuid.toString());
        });
    }
    void accept(Snapshot snapshot) {
        Snapshot old=snapshot.active() ? baseline.put(snapshot.sign(),snapshot) : baseline.remove(snapshot.sign());
        if(old==null || !old.generation().equals(snapshot.generation()) || !old.owner().equals(snapshot.owner())) return;
        if(snapshot.active() && old.items().equals(snapshot.items())) return;
        long now=clock.getAsLong(), departed=presence.getOrDefault(snapshot.owner(),started);
        boolean eligible=config.enabled() && departed>=0 && now-departed>=config.absenceMillis();
        if(eligible) enqueue(()->observe(old,snapshot,now));
    }
    private void observe(Snapshot old,Snapshot current,long now) throws Exception {
        Map<String,Long> changes=new TreeMap<>();
        if(current.active()) {
            Set<String> keys=new HashSet<>(old.items().keySet()); keys.addAll(current.items().keySet());
            for(String item:keys) {
                long delta=current.items().getOrDefault(item,0L)-old.items().getOrDefault(item,0L);
                if(delta!=0) changes.put(item,delta);
            }
        }
        BlockKey p=old.chests().getFirst();
        String location="Мир "+p.world()+"; блок "+p.x()+" "+p.y()+" "+p.z();
        Event event=new Event(0,now,old.playerName(),location,changes,!current.active());
        db.setAutoCommit(false);
        try {
            long id;
            try(var s=db.prepareStatement("INSERT INTO events(happened,payload) VALUES(?,?)",Statement.RETURN_GENERATED_KEYS)) {
                s.setLong(1,now);s.setString(2,gson.toJson(event));s.executeUpdate();
                try(var rs=s.getGeneratedKeys()) {rs.next();id=rs.getLong(1);}
            }
            Set<Long> recipients=new HashSet<>();
            try(var s=db.prepareStatement("SELECT tg FROM accounts WHERE uuid=? AND alerts=TRUE")) {
                s.setString(1,old.owner().toString()); try(var rs=s.executeQuery()) {if(rs.next()) recipients.add(rs.getLong(1));}
            }
            for(long admin:admins) if(adminAlertsNow(admin)) recipients.add(admin);
            String message="🛡 Изменение хранилища во время отсутствия владельца\n"+eventText(event,0,12)+"\nСобытие #"+id+". Подробности доступны администратору в истории.";
            for(long recipient:recipients) execute("INSERT INTO outbox(event_id,tg,owner_uuid,body,due,created) VALUES(?,?,?,?,?,?)",id,recipient,old.owner().toString(),message,now,now);
            db.commit();
        } catch(Exception e) {db.rollback();throw e;} finally {db.setAutoCommit(true);}
        prune();
    }
    CompletableFuture<String> generate(long user) {return submit(()-> {
        if(accountNow(user)!=null) return "Персонаж уже привязан. Откройте кабинет.";
        long now=clock.getAsLong(); codes.entrySet().removeIf(e->e.getValue().expires()<=now || e.getValue().user()==user);
        byte[] bytes=new byte[16];random.nextBytes(bytes);
        String code=HexFormat.of().formatHex(bytes); codes.put(code,new Code(user,now+CODE_TTL));
        return "Выполните в Minecraft под своим персонажем:\n/vtrack link "+code+"\n\nКод одноразовый, действует 10 минут. Не передавайте его другим игрокам. После выполнения нажмите «Обновить кабинет».";
    });}
    CompletableFuture<String> link(UUID uuid,String name,String token) {return submit(()-> {
        Code code=codes.get(token);
        if(code==null || code.expires()<=clock.getAsLong()) return "Код неверный или истёк. Получите новый в личном чате бота.";
        if(accountNow(code.user())!=null) return "Этот Telegram-аккаунт уже привязан.";
        try(var s=db.prepareStatement("SELECT tg FROM accounts WHERE uuid=?")) {
            s.setString(1,uuid.toString());try(var rs=s.executeQuery()) {if(rs.next()) return "Ваш персонаж уже привязан к Telegram. Повторная привязка запрещена.";}
        }
        execute("INSERT INTO accounts(tg,uuid,nickname,alerts) VALUES(?,?,?,TRUE)",code.user(),uuid.toString(),name);
        codes.remove(token);
        return "Персонаж "+name+" привязан к Telegram. В боте нажмите «Обновить кабинет» или /menu. Уведомления о ваших хранилищах включены.";
    });}
    CompletableFuture<Account> account(long user) {return submit(()->accountNow(user));}
    private Account accountNow(long user) throws Exception {
        try(var s=db.prepareStatement("SELECT uuid,nickname,alerts FROM accounts WHERE tg=?")) {
            s.setLong(1,user);try(var rs=s.executeQuery()) {return rs.next() ? new Account(UUID.fromString(rs.getString(1)),rs.getString(2),rs.getBoolean(3)) : null;}
        }
    }
    CompletableFuture<Void> toggleOwn(long user) {return submit(()-> {execute("UPDATE accounts SET alerts=NOT alerts WHERE tg=?",user);return null;});}
    CompletableFuture<Boolean> adminAlerts(long user) {return submit(()->adminAlertsNow(user));}
    private boolean adminAlertsNow(long user) throws Exception {
        try(var s=db.prepareStatement("SELECT alerts FROM preferences WHERE tg=?")) {
            s.setLong(1,user);try(var rs=s.executeQuery()) {return !rs.next() || rs.getBoolean(1);}
        }
    }
    CompletableFuture<Void> toggleAdmin(long user) {return submit(()-> {
        if(!admin(user)) throw new SecurityException("Нет доступа");
        execute("MERGE INTO preferences KEY(tg) VALUES(?,?)",user,!adminAlertsNow(user));return null;
    });}
    CompletableFuture<List<Event>> history(long user,int page,int size) {return submit(()-> {
        if(!admin(user)) throw new SecurityException("Нет доступа");
        prune(); List<Event> result=new ArrayList<>();
        try(var s=db.prepareStatement("SELECT id,payload FROM events WHERE happened>=? ORDER BY id DESC LIMIT ? OFFSET ?")) {
            s.setLong(1,clock.getAsLong()-RETENTION);s.setInt(2,size);s.setLong(3,(long)Math.max(0,page)*size);
            try(var rs=s.executeQuery()) {while(rs.next()) {Event e=gson.fromJson(rs.getString(2),Event.class);result.add(new Event(rs.getLong(1),e.time(),e.name(),e.location(),e.changes(),e.removed()));}}
        }
        return result;
    });}
    CompletableFuture<Event> event(long user,long id) {return submit(()-> {
        if(!admin(user)) throw new SecurityException("Нет доступа");
        try(var s=db.prepareStatement("SELECT payload FROM events WHERE id=? AND happened>=?")) {
            s.setLong(1,id);s.setLong(2,clock.getAsLong()-RETENTION);
            try(var rs=s.executeQuery()) {if(!rs.next()) return null;Event e=gson.fromJson(rs.getString(1),Event.class);return new Event(id,e.time(),e.name(),e.location(),e.changes(),e.removed());}
        }
    });}
    CompletableFuture<List<Delivery>> deliveries() {return submit(()-> {
        prune(); if(!config.enabled()) return List.of();
        List<Delivery> result=new ArrayList<>();List<Long> discard=new ArrayList<>();
        try(var s=db.prepareStatement("SELECT id,tg,owner_uuid,body FROM outbox WHERE due<=? ORDER BY id LIMIT 20")) {
            s.setLong(1,clock.getAsLong());try(var rs=s.executeQuery()) {while(rs.next()) {
                long id=rs.getLong(1),tg=rs.getLong(2);Account a=accountNow(tg);
                if((admin(tg) && adminAlertsNow(tg)) || (a!=null && a.notifications() && a.uuid().toString().equals(rs.getString(3))))
                    result.add(new Delivery(id,tg,rs.getString(4)));
                else discard.add(id);
            }}
        }
        for(long id:discard) execute("DELETE FROM outbox WHERE id=?",id);
        return result;
    });}
    CompletableFuture<Void> delivered(long id,boolean success) {return submit(()-> {
        if(success) execute("DELETE FROM outbox WHERE id=?",id);
        else execute("UPDATE outbox SET due=? WHERE id=?",clock.getAsLong()+300_000,id);
        return null;
    });}
    private void prune() throws Exception {
        long now=clock.getAsLong();if(now-lastPrune<60_000) return;
        execute("DELETE FROM outbox WHERE created<?",now-RETENTION);
        execute("DELETE FROM events WHERE happened<?",now-RETENTION);lastPrune=now;
    }
    static String eventText(Event event,int offset,int limit) {
        StringBuilder text=new StringBuilder(event.name()).append(" • ")
                .append(java.time.Instant.ofEpochMilli(event.time()).atZone(java.time.ZoneId.systemDefault()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss z")))
                .append('\n').append(event.location()).append('\n');
        if(event.removed()) return text.append("Хранилище снято с учёта: табличка/контейнер удалены или регистрация отменена. Это не подтверждение кражи вещей.").toString();
        var rows=event.changes().entrySet().stream().sorted(Map.Entry.comparingByKey()).toList();
        for(int i=offset;i<Math.min(rows.size(),offset+limit);i++) {
            var r=rows.get(i);text.append(TelegramItemIcons.label(r.getKey())).append(": ").append(r.getValue()>0 ? "+" : "").append(r.getValue()).append(" шт.\n");
        }
        if(rows.size()>offset+limit) text.append("Ещё позиций: ").append(rows.size()-offset-limit).append('\n');
        return text.toString().stripTrailing();
    }
    private void execute(String sql,Object... args) throws SQLException {
        try(var s=db.prepareStatement(sql)) {for(int i=0;i<args.length;i++) s.setObject(i+1,args[i]);s.executeUpdate();}
    }
    private <T> CompletableFuture<T> submit(Callable<T> task) {
        CompletableFuture<T> future=new CompletableFuture<>();
        try {disk.execute(()-> {try {future.complete(task.call());} catch(Exception e) {future.completeExceptionally(e);}});}
        catch(RejectedExecutionException e) {future.completeExceptionally(e);}return future;
    }
    private void enqueue(Checked task) {submit(()-> {task.run();return null;}).exceptionally(e-> {log.severe("Ошибка сохранения охраны: "+e.getClass().getSimpleName()+". Проверьте guard-data и доступ к диску.");return null;});}
    @FunctionalInterface private interface Checked {void run() throws Exception;}
    @Override public void close() {
        enqueue(()-> {try {execute("UPDATE presence SET departed=? WHERE departed<0",clock.getAsLong());} finally {db.close();}});
        disk.shutdown();try {if(!disk.awaitTermination(10,TimeUnit.SECONDS)) log.severe("Охрана не завершила сохранение за 10 секунд.");}
        catch(InterruptedException e) {Thread.currentThread().interrupt();}
    }
}
