package ru.vaulttracker;

import com.google.gson.Gson;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.LongSupplier;
import java.util.logging.Logger;

/** Dedicated disk worker: region threads only enqueue immutable snapshots and presence changes. */
final class GuardService implements AutoCloseable {
    static final long RETENTION=30L*24*60*60*1000, CODE_TTL=10*60*1000L;
    static final long MAX_OFFLINE_SECONDS=31_536_000;
    record Account(UUID uuid,String name,boolean notifications) {}
    record Event(long id,long time,String name,String location,Map<String,Long> changes,boolean removed,String actor) {}
    record Delivery(long id,long recipient,String text) {}
    private record Code(long user,long expires) {}
    private final ScheduledExecutorService disk=Executors.newSingleThreadScheduledExecutor(r->new Thread(r,"VaultTracker-guard-disk"));
    private final Connection db;
    private final Logger log;
    private final LongSupplier clock;
    private final long started;
    private final Map<UUID,Long> presence=new ConcurrentHashMap<>(); // -1 online, otherwise exit timestamp
    private final Map<UUID,Long> personalAbsence=new ConcurrentHashMap<>();
    private final Map<UUID,String> worlds=new ConcurrentHashMap<>();
    private final Map<BlockKey,Actor> actors=new ConcurrentHashMap<>();
    private record Actor(UUID uuid,String name,long expires) {}
    private final Map<BlockKey,Snapshot> baseline=new ConcurrentHashMap<>();
    private final Map<String,Code> codes=new HashMap<>();
    private final SecureRandom random=new SecureRandom();
    private final Gson gson=new Gson();
    private volatile GuardConfig config;
    private volatile Set<Long> admins=Set.of();
    private final Map<Long,Boolean> adminOverrides=new ConcurrentHashMap<>();
    private final Map<Long,Long> superDelays=new ConcurrentHashMap<>();
    private long lastPrune;

    GuardService(Path path,GuardConfig config,Logger log) throws Exception { this(path,config,log,System::currentTimeMillis); }
    GuardService(Path path,GuardConfig config,Logger log,LongSupplier clock) throws Exception {
        this.config=config; this.log=log; this.clock=clock; started=clock.getAsLong();
        Class.forName("org.h2.Driver");
        db=DriverManager.getConnection("jdbc:h2:"+path.toAbsolutePath()+";DB_CLOSE_ON_EXIT=FALSE","sa","");
        try(var s=db.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS accounts (tg BIGINT PRIMARY KEY, uuid VARCHAR(36) UNIQUE NOT NULL, nickname VARCHAR(64) NOT NULL, alerts BOOLEAN NOT NULL DEFAULT TRUE)");
            s.execute("ALTER TABLE accounts ADD COLUMN IF NOT EXISTS offline_seconds BIGINT");
            s.execute("ALTER TABLE accounts ADD COLUMN IF NOT EXISTS telegram_tag BOOLEAN NOT NULL DEFAULT FALSE");
            s.execute("CREATE TABLE IF NOT EXISTS guard_admins (tg BIGINT PRIMARY KEY, enabled BOOLEAN NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS super_delays (tg BIGINT PRIMARY KEY, seconds BIGINT NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS guard_worlds (uuid VARCHAR(36) PRIMARY KEY, world_name VARCHAR(256) NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS preferences (tg BIGINT PRIMARY KEY, alerts BOOLEAN NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS presence (uuid VARCHAR(36) PRIMARY KEY, departed BIGINT NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, happened BIGINT NOT NULL, payload CLOB NOT NULL)");
            s.execute("ALTER TABLE events ADD COLUMN IF NOT EXISTS owner_uuid VARCHAR(36)");
            s.execute("CREATE INDEX IF NOT EXISTS guard_owner_events ON events(owner_uuid,happened)");
            s.execute("CREATE TABLE IF NOT EXISTS outbox (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id BIGINT, tg BIGINT NOT NULL, owner_uuid VARCHAR(36), body CLOB NOT NULL, due BIGINT NOT NULL, created BIGINT NOT NULL)");
            s.execute("ALTER TABLE outbox ADD COLUMN IF NOT EXISTS own_channel BOOLEAN NOT NULL DEFAULT TRUE");
            s.execute("ALTER TABLE outbox ADD COLUMN IF NOT EXISTS admin_channel BOOLEAN NOT NULL DEFAULT TRUE");
            s.execute("CREATE INDEX IF NOT EXISTS guard_event_time ON events(happened)");
            s.execute("CREATE INDEX IF NOT EXISTS guard_outbox_due ON outbox(due)");
        }
        try(var s=db.createStatement();var rs=s.executeQuery("SELECT uuid,offline_seconds FROM accounts WHERE offline_seconds IS NOT NULL")) {
            while(rs.next()) personalAbsence.put(UUID.fromString(rs.getString(1)),rs.getLong(2)*1000);
        }
        try(var s=db.createStatement();var rs=s.executeQuery("SELECT uuid,world_name FROM guard_worlds")) {
            while(rs.next()) worlds.put(UUID.fromString(rs.getString(1)),rs.getString(2));
        }
        try(var s=db.createStatement();var rs=s.executeQuery("SELECT uuid, departed FROM presence")) {
            while(rs.next()) presence.put(UUID.fromString(rs.getString(1)),rs.getLong(2)<0 ? started : rs.getLong(2));
        }
        execute("UPDATE presence SET departed=? WHERE departed<0",started);
        try(var s=db.createStatement();var rs=s.executeQuery("SELECT tg,enabled FROM guard_admins")) {while(rs.next()) adminOverrides.put(rs.getLong(1),rs.getBoolean(2));}
        try(var s=db.createStatement();var rs=s.executeQuery("SELECT tg,seconds FROM super_delays")) {while(rs.next()) superDelays.put(rs.getLong(1),rs.getLong(2));}
        disk.scheduleWithFixedDelay(()-> {try {prune();} catch(Exception e) {log.warning("Не удалось очистить историю охраны.");}},1,60,TimeUnit.MINUTES);
    }
    void configure(GuardConfig config,Set<Long> admins) { this.config=config; this.admins=Set.copyOf(admins); }
    boolean superAdmin(long user) {return user>0 && config.superAdminUserId()==user;}
    boolean admin(long user) { return superAdmin(user) || adminOverrides.getOrDefault(user,admins.contains(user)); }
    Set<Long> adminIds() {
        Set<Long> ids=new TreeSet<>(admins);adminOverrides.forEach((id,enabled)-> {if(enabled) ids.add(id);else ids.remove(id);});
        if(config.superAdminUserId()>0) ids.add(config.superAdminUserId());return ids;
    }
    void requireAdmin(long user) {if(!admin(user)) throw new SecurityException("Требуются права администратора");}
    void requireSuper(long user) {if(!superAdmin(user)) throw new SecurityException("Требуются права супер администратора");}
    CompletableFuture<Void> changeAdmin(long user,long target,boolean enabled) {return submit(()-> {
        requireSuper(user);if(target<=0 || superAdmin(target)) throw new IllegalArgumentException("Нельзя изменить эту роль");
        execute("MERGE INTO guard_admins KEY(tg) VALUES(?,?)",target,enabled);adminOverrides.put(target,enabled);
        log.info("Telegram "+user+": администратор "+target+" → "+enabled);return null;
    });}
    CompletableFuture<Boolean> tag(long user,boolean toggle) {return submit(()-> {
        if(accountNow(user)==null) throw new SecurityException("Сначала привяжите персонажа");
        if(toggle) execute("UPDATE accounts SET telegram_tag=NOT telegram_tag WHERE tg=?",user);
        try(var s=db.prepareStatement("SELECT telegram_tag FROM accounts WHERE tg=?")) {s.setLong(1,user);try(var rs=s.executeQuery()) {rs.next();return rs.getBoolean(1);}}
    });}
    CompletableFuture<Void> setTag(long user,boolean enabled) {return submit(()-> {
        if(accountNow(user)==null) throw new SecurityException("Сначала привяжите персонажа");
        execute("UPDATE accounts SET telegram_tag=? WHERE tg=?",enabled,user);return null;
    });}
    long superDelay(long user) {requireSuper(user);return superDelays.getOrDefault(user,defaultOfflineSeconds());}
    CompletableFuture<Void> superDelay(long user,long seconds) {return submit(()-> {
        if(seconds== -2) {requireSuper(user);execute("DELETE FROM super_delays WHERE tg=?",user);superDelays.remove(user);return null;}
        requireSuper(user);if(seconds < -1 || seconds>MAX_OFFLINE_SECONDS) throw new IllegalArgumentException("Время вне диапазона");
        execute("MERGE INTO super_delays KEY(tg) VALUES(?,?)",user,seconds);superDelays.put(user,seconds);return null;
    });}
    boolean enabled() { return config.enabled(); }
    long defaultOfflineSeconds() {return config.absenceMillis()/1000;}
    void world(UUID uuid,String name) {
        worlds.put(uuid,name);
        enqueue(()->execute("MERGE INTO guard_worlds KEY(uuid) VALUES(?,?)",uuid.toString(),name));
    }
    String readableLocation(String text) {
        var pattern=java.util.regex.Pattern.compile("Мир ([0-9a-fA-F-]{36}); блок (-?\\d+ -?\\d+ -?\\d+)");
        var matcher=pattern.matcher(text);StringBuilder result=new StringBuilder();
        while(matcher.find()) {
            String name=worlds.getOrDefault(UUID.fromString(matcher.group(1)),"неизвестный мир");
            matcher.appendReplacement(result,java.util.regex.Matcher.quoteReplacement("Мир: "+name+"\nКоординаты: "+matcher.group(2)));
        }
        matcher.appendTail(result);return result.toString();
    }
    CompletableFuture<Long> offlineSeconds(long user) {return submit(()-> {
        Account a=accountNow(user);if(a==null) throw new SecurityException("Сначала привяжите персонажа");
        Long millis=personalAbsence.get(a.uuid());return millis==null ? null : millis/1000;
    });}
    CompletableFuture<Void> offlineSeconds(long user,Long seconds) {return submit(()-> {
        if(seconds!=null && (seconds< -1 || seconds>MAX_OFFLINE_SECONDS)) throw new IllegalArgumentException("Время вне диапазона");
        Account a=accountNow(user);if(a==null) throw new SecurityException("Сначала привяжите персонажа");
        execute("UPDATE accounts SET offline_seconds=? WHERE tg=?",seconds,user);
        if(seconds==null) personalAbsence.remove(a.uuid());else personalAbsence.put(a.uuid(),seconds*1000);
        return null;
    });}
    void restore(Collection<Snapshot> snapshots) {for(var v:snapshots) if(v.active()) baseline.put(v.sign(),v);}
    void attribute(BlockKey sign,UUID playerId,String playerName) {
        if(playerId!=null && playerName!=null && !playerName.isBlank()) actors.put(sign,new Actor(playerId,playerName,clock.getAsLong()+30_000));
    }
    /** Kept for compatibility with old callers that cannot identify the player. */
    void attribute(BlockKey sign,String playerName) {
        if(playerName!=null && !playerName.isBlank()) actors.put(sign,new Actor(null,playerName,clock.getAsLong()+30_000));
    }
    void presence(UUID uuid,String name,boolean online) {
        long time=online ? -1 : clock.getAsLong(); presence.put(uuid,time);
        enqueue(()-> {
            execute("MERGE INTO presence KEY(uuid) VALUES(?,?)",uuid.toString(),time);
            if(online) execute("UPDATE accounts SET nickname=? WHERE uuid=?",name,uuid.toString());
        });
    }
    void accept(Snapshot snapshot) {
        Actor attributed=actors.remove(snapshot.sign());
        Actor actorInfo=attributed!=null && attributed.expires()>=clock.getAsLong() ? attributed : null;
        String actor=actorInfo==null ? null : actorInfo.name();
        Snapshot old=snapshot.active() ? baseline.put(snapshot.sign(),snapshot) : baseline.remove(snapshot.sign());
        if(old==null || !old.generation().equals(snapshot.generation()) || !old.owner().equals(snapshot.owner())) return;
        if(snapshot.active() && old.items().equals(snapshot.items())) return;
        // The owner working with their own storage is expected activity, not an incident.
        if(actorInfo!=null && snapshot.owner().equals(actorInfo.uuid())) return;
        long now=clock.getAsLong(), departed=presence.getOrDefault(snapshot.owner(),started);
        GuardConfig settings=config;
        if(!settings.enabled()) return;
        long ownDelay=personalAbsence.getOrDefault(snapshot.owner(),settings.absenceMillis());
        boolean ownEligible=ownDelay<0 || (departed>=0 && now-departed>=ownDelay);
        boolean adminEligible=departed>=0 && now-departed>=settings.absenceMillis();
        long root=settings.superAdminUserId(),rootDelay=superDelays.getOrDefault(root,settings.absenceMillis()/1000)*1000;
        boolean rootEligible=root>0 && (rootDelay<0 || (departed>=0 && now-departed>=rootDelay));
        if(ownEligible || adminEligible || rootEligible) enqueue(()->observe(old,snapshot,now,ownEligible,adminEligible,actor,rootEligible,root));
    }
    private void observe(Snapshot old,Snapshot current,long now,boolean ownEligible,boolean adminEligible,String actor,boolean rootEligible,long root) throws Exception {
        Map<String,Long> changes=new TreeMap<>();
        if(current.active()) {
            Set<String> keys=new HashSet<>(old.items().keySet()); keys.addAll(current.items().keySet());
            for(String item:keys) {
                long delta=current.items().getOrDefault(item,0L)-old.items().getOrDefault(item,0L);
                if(delta!=0) changes.put(item,delta);
            }
        }
        BlockKey p=old.chests().getFirst();
        String location=readableLocation("Мир "+p.world()+"; блок "+p.x()+" "+p.y()+" "+p.z());
        Event event=new Event(0,now,old.playerName(),location,changes,!current.active(),actor);
        db.setAutoCommit(false);
        try {
            long id;
            try(var s=db.prepareStatement("INSERT INTO events(happened,payload,owner_uuid) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)) {
                s.setLong(1,now);s.setString(2,gson.toJson(event));s.setString(3,old.owner().toString());s.executeUpdate();
                try(var rs=s.getGeneratedKeys()) {rs.next();id=rs.getLong(1);}
            }
            Set<Long> recipients=new HashSet<>();
            Long ownerRecipient=null;
            try(var s=db.prepareStatement("SELECT tg FROM accounts WHERE uuid=? AND alerts=TRUE")) {
                s.setString(1,old.owner().toString()); try(var rs=s.executeQuery()) {if(rs.next() && ownEligible) {ownerRecipient=rs.getLong(1);recipients.add(ownerRecipient);}}
            }
            Set<Long> adminRecipients=new HashSet<>();
            for(long admin:adminIds()) if((admin==root ? rootEligible : adminEligible) && adminAlertsNow(admin)) {recipients.add(admin);adminRecipients.add(admin);}
            String base="🛡 Изменение хранилища\n"+eventText(event,0,12,false);
            for(long recipient:recipients) {
                boolean adminChannel=adminRecipients.contains(recipient);
                String message=base+(adminChannel ? "\nКто изменил: "+(actor==null ? "не определено (механизм, взрыв или другое обстоятельство)" : actor) : "")
                        +"\nСобытие #"+id+". Подробности доступны администратору в истории.";
                execute("INSERT INTO outbox(event_id,tg,owner_uuid,body,due,created,own_channel,admin_channel) VALUES(?,?,?,?,?,?,?,?)",id,recipient,old.owner().toString(),message,now,now,Objects.equals(ownerRecipient,recipient),adminChannel);
            }
            db.commit();
        } catch(Exception e) {db.rollback();throw e;} finally {db.setAutoCommit(true);}
        prune();
    }
    CompletableFuture<String> generate(long user) {return submit(()-> {
        if(accountNow(user)!=null) return "Персонаж уже привязан. Откройте кабинет.";
        long now=clock.getAsLong(); codes.entrySet().removeIf(e->e.getValue().expires()<=now || e.getValue().user()==user);
        byte[] bytes=new byte[16];random.nextBytes(bytes);
        String code=HexFormat.of().formatHex(bytes); codes.put(code,new Code(user,now+CODE_TTL));
        return "Выполните в Minecraft под своим персонажем:\n/vtrack link "+code+"\n\nКод одноразовый, действует 10 минут. Не передавайте его другим игрокам. После выполнения нажмите «Обновить кабинет».";
    });}
    CompletableFuture<String> link(UUID uuid,String name,String token) {return submit(()-> {
        Code code=codes.get(token);
        if(code==null || code.expires()<=clock.getAsLong()) return "Код неверный или истёк. Получите новый в личном чате бота.";
        if(accountNow(code.user())!=null) return "Этот Telegram-аккаунт уже привязан.";
        try(var s=db.prepareStatement("SELECT tg FROM accounts WHERE uuid=?")) {
            s.setString(1,uuid.toString());try(var rs=s.executeQuery()) {if(rs.next()) return "Ваш персонаж уже привязан к Telegram. Повторная привязка запрещена.";}
        }
        execute("INSERT INTO accounts(tg,uuid,nickname,alerts) VALUES(?,?,?,TRUE)",code.user(),uuid.toString(),name);
        codes.remove(token);
        return "Персонаж "+name+" привязан к Telegram. В боте нажмите «Обновить кабинет» или /menu. Уведомления о ваших хранилищах включены.";
    });}
    CompletableFuture<Account> account(long user) {return submit(()->accountNow(user));}
    private Account accountNow(long user) throws Exception {
        try(var s=db.prepareStatement("SELECT uuid,nickname,alerts FROM accounts WHERE tg=?")) {
            s.setLong(1,user);try(var rs=s.executeQuery()) {return rs.next() ? new Account(UUID.fromString(rs.getString(1)),rs.getString(2),rs.getBoolean(3)) : null;}
        }
    }
    CompletableFuture<Void> toggleOwn(long user) {return submit(()-> {execute("UPDATE accounts SET alerts=NOT alerts WHERE tg=?",user);return null;});}
    CompletableFuture<Boolean> adminAlerts(long user) {return submit(()->adminAlertsNow(user));}
    private boolean adminAlertsNow(long user) throws Exception {
        try(var s=db.prepareStatement("SELECT alerts FROM preferences WHERE tg=?")) {
            s.setLong(1,user);try(var rs=s.executeQuery()) {return !rs.next() || rs.getBoolean(1);}
        }
    }
    CompletableFuture<Void> toggleAdmin(long user) {return submit(()-> {
        if(!admin(user)) throw new SecurityException("Нет доступа");
        execute("MERGE INTO preferences KEY(tg) VALUES(?,?)",user,!adminAlertsNow(user));return null;
    });}
    CompletableFuture<List<Event>> history(long user,int page,int size) {return submit(()-> {
        if(!admin(user)) throw new SecurityException("Нет доступа");
        prune(); List<Event> result=new ArrayList<>();
        try(var s=db.prepareStatement("SELECT id,payload FROM events WHERE happened>=? ORDER BY id DESC LIMIT ? OFFSET ?")) {
            s.setLong(1,clock.getAsLong()-RETENTION);s.setInt(2,size);s.setLong(3,(long)Math.max(0,page)*size);
            try(var rs=s.executeQuery()) {while(rs.next()) {Event e=gson.fromJson(rs.getString(2),Event.class);result.add(new Event(rs.getLong(1),e.time(),e.name(),readableLocation(e.location()),e.changes(),e.removed(),e.actor()));}}
        }
        return result;
    });}
    CompletableFuture<List<Event>> ownHistory(long user,int page,int size) {return submit(()-> {
        Account a=accountNow(user);if(a==null) throw new SecurityException("Нет привязки");
        List<Event> result=new ArrayList<>();
        try(var s=db.prepareStatement("SELECT id,payload FROM events WHERE owner_uuid=? AND happened>=? ORDER BY id DESC LIMIT ? OFFSET ?")) {
            s.setString(1,a.uuid().toString());s.setLong(2,clock.getAsLong()-2L*86400_000);s.setInt(3,size);s.setLong(4,(long)Math.max(0,page)*size);
            try(var rs=s.executeQuery()) {while(rs.next()) {Event e=gson.fromJson(rs.getString(2),Event.class);result.add(new Event(rs.getLong(1),e.time(),e.name(),readableLocation(e.location()),e.changes(),e.removed(),null));}}
        }return result;
    });}
    CompletableFuture<Event> ownEvent(long user,long id) {return submit(()-> {
        Account a=accountNow(user);if(a==null) throw new SecurityException("Нет привязки");
        try(var s=db.prepareStatement("SELECT payload FROM events WHERE id=? AND owner_uuid=? AND happened>=?")) {
            s.setLong(1,id);s.setString(2,a.uuid().toString());s.setLong(3,clock.getAsLong()-2L*86400_000);
            try(var rs=s.executeQuery()) {if(!rs.next()) return null;Event e=gson.fromJson(rs.getString(1),Event.class);return new Event(id,e.time(),e.name(),readableLocation(e.location()),e.changes(),e.removed(),null);}
        }
    });}
    CompletableFuture<Event> event(long user,long id) {return submit(()-> {
        if(!admin(user)) throw new SecurityException("Нет доступа");
        try(var s=db.prepareStatement("SELECT payload FROM events WHERE id=? AND happened>=?")) {
            s.setLong(1,id);s.setLong(2,clock.getAsLong()-RETENTION);
            try(var rs=s.executeQuery()) {if(!rs.next()) return null;Event e=gson.fromJson(rs.getString(1),Event.class);return new Event(id,e.time(),e.name(),readableLocation(e.location()),e.changes(),e.removed(),e.actor());}
        }
    });}
    CompletableFuture<List<Delivery>> deliveries() {return submit(()-> {
        prune(); if(!config.enabled()) return List.of();
        List<Delivery> result=new ArrayList<>();List<Long> discard=new ArrayList<>();
        try(var s=db.prepareStatement("SELECT id,tg,owner_uuid,body,own_channel,admin_channel FROM outbox WHERE due<=? ORDER BY id LIMIT 20")) {
            s.setLong(1,clock.getAsLong());try(var rs=s.executeQuery()) {while(rs.next()) {
                long id=rs.getLong(1),tg=rs.getLong(2);Account a=accountNow(tg);
                if((rs.getBoolean(6) && admin(tg) && adminAlertsNow(tg)) || (rs.getBoolean(5) && a!=null && a.notifications() && a.uuid().toString().equals(rs.getString(3))))
                    result.add(new Delivery(id,tg,(rs.getBoolean(6) && admin(tg) && adminAlertsNow(tg)) ? readableLocation(rs.getString(4)) : readableLocation(rs.getString(4)).replaceAll("\\nКто изменил:[^\\n]*","")));
                else discard.add(id);
            }}
        }
        for(long id:discard) execute("DELETE FROM outbox WHERE id=?",id);
        return result;
    });}
    CompletableFuture<Void> delivered(long id,boolean success) {return submit(()-> {
        if(success) execute("DELETE FROM outbox WHERE id=?",id);
        else execute("UPDATE outbox SET due=? WHERE id=?",clock.getAsLong()+300_000,id);
        return null;
    });}
    private void prune() throws Exception {
        long now=clock.getAsLong();if(now-lastPrune<60_000) return;
        execute("DELETE FROM outbox WHERE created<?",now-RETENTION);
        execute("DELETE FROM events WHERE happened<?",now-RETENTION);lastPrune=now;
    }
    static String eventText(Event event,int offset,int limit) {
        return eventText(event,offset,limit,true);
    }
    static String eventText(Event event,int offset,int limit,boolean showActor) {
        StringBuilder text=new StringBuilder(event.name()).append(" • ")
                .append(java.time.Instant.ofEpochMilli(event.time()).atZone(java.time.ZoneId.systemDefault()).format(java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss z")))
                .append('\n').append(event.location()).append('\n');
        if(event.removed()) {
            text.append("Хранилище снято с учёта: табличка/контейнер удалены или регистрация отменена. Это не подтверждение кражи вещей.");
            if(showActor) text.append("\nКто изменил: ").append(event.actor()==null ? "не определено" : event.actor());
            return text.toString();
        }
        var rows=event.changes().entrySet().stream().sorted(Map.Entry.comparingByKey()).toList();
        for(int i=offset;i<Math.min(rows.size(),offset+limit);i++) {
            var r=rows.get(i);text.append(TelegramItemIcons.label(r.getKey())).append(": ").append(r.getValue()>0 ? "+" : "").append(r.getValue()).append(" шт.\n");
        }
        if(rows.size()>offset+limit) text.append("Ещё позиций: ").append(rows.size()-offset-limit).append('\n');
        if(showActor) text.append("Кто изменил: ").append(event.actor()==null ? "не определено" : event.actor()).append('\n');
        return text.toString().stripTrailing();
    }
    private void execute(String sql,Object... args) throws SQLException {
        try(var s=db.prepareStatement(sql)) {for(int i=0;i<args.length;i++) s.setObject(i+1,args[i]);s.executeUpdate();}
    }
    private <T> CompletableFuture<T> submit(Callable<T> task) {
        CompletableFuture<T> future=new CompletableFuture<>();
        try {disk.execute(()-> {try {future.complete(task.call());} catch(Exception e) {future.completeExceptionally(e);}});}
        catch(RejectedExecutionException e) {future.completeExceptionally(e);}return future;
    }
    private void enqueue(Checked task) {submit(()-> {task.run();return null;}).exceptionally(e-> {log.severe("Ошибка сохранения охраны: "+e.getClass().getSimpleName()+". Проверьте guard-data и доступ к диску.");return null;});}
    @FunctionalInterface private interface Checked {void run() throws Exception;}
    @Override public void close() {
        enqueue(()-> {try {execute("UPDATE presence SET departed=? WHERE departed<0",clock.getAsLong());} finally {db.close();}});
        disk.shutdown();try {if(!disk.awaitTermination(10,TimeUnit.SECONDS)) log.severe("Охрана не завершила сохранение за 10 секунд.");}
        catch(InterruptedException e) {Thread.currentThread().interrupt();}
    }
}
