package ru.vaulttracker;

import com.google.gson.Gson;
import java.nio.file.Path;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Logger;

/** Telegram-only moderation. Never executes Minecraft or system commands. */
final class TelegramReports implements AutoCloseable {
    private static final Set<String> COMMANDS=Set.of("/report","/mute","/unmute","/ban","/unban","/warn","/warnings","/unwarn","/clearwarns","/modhelp");
    record Report(String id,long chat,int topic,int sourceMessage,long target,String name,String text,String reason,String reporter,int reportMessage) {}
    private final TelegramChatConfig config;
    private final TelegramApi api;
    private final TelegramListExpiry expiry;
    private final Logger log;
    private final Connection db;
    private final Gson gson=new Gson();
    private final ThreadPoolExecutor worker=new ThreadPoolExecutor(1,1,0,TimeUnit.SECONDS,new ArrayBlockingQueue<>(500),Thread.ofVirtual().name("VaultTracker-reports").factory());
    private final Map<String,Long> cooldown=new HashMap<>();
    private volatile boolean closed;
    TelegramReports(Path folder,TelegramChatConfig config,TelegramApi api,TelegramListExpiry expiry,Logger log) throws Exception {
        this.config=config;this.api=api;this.expiry=expiry;this.log=log;
        Class.forName("org.h2.Driver");db=DriverManager.getConnection("jdbc:h2:"+folder.resolve("telegramchat-moderation-"+config.token.split(":",2)[0]).toAbsolutePath()+";DB_CLOSE_ON_EXIT=FALSE","sa","");
        try(var s=db.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS reports (id VARCHAR(32) PRIMARY KEY, payload CLOB NOT NULL, state VARCHAR(16) NOT NULL)");
            s.execute("CREATE TABLE IF NOT EXISTS warnings (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat BIGINT NOT NULL, target BIGINT NOT NULL, reason VARCHAR(1000) NOT NULL)");
        }
    }
    boolean consume(TelegramApi.Incoming update,String username) {
        if(closed||update.privateChat()||update.senderBot()) return false;
        boolean callback=update.callback()&&update.callbackData()!=null&&update.callbackData().startsWith("vtr:");
        if(callback) {if(!config.reports.matches(update)) return false;}
        else {
            if(update.text()==null||!sourceGroup(update.chatId())) return false;
            String[] name=update.text().trim().split("\\s+",2)[0].split("@",2);
            if(!COMMANDS.contains(name[0].toLowerCase(Locale.ROOT))||(name.length==2&&(username==null||!name[1].equalsIgnoreCase(username)))) return false;
        }
        try {worker.execute(()->{
            if(closed) return;
            try {if(callback) callback(update);else command(update);}
            catch(IllegalArgumentException invalid) {try {if(callback) api.answerCallback(update.callbackId(),invalid.getMessage(),true);else notice(update,invalid.getMessage());}catch(Exception ignored){}}
            catch(Exception failure) {
                log.warning("Telegram-репорты: "+api.safe(failure));
                try {if(callback) api.answerCallback(update.callbackId(),"Действие не выполнено. Проверьте права бота; подробности в журнале сервера.",true);
                    else notice(update,"Действие не выполнено. Проверьте ответ на сообщение, права бота и повторите команду.");} catch(Exception ignored) {}
            }
        });} catch(RejectedExecutionException full) {log.warning("Очередь репортов заполнена; повторите команду позже.");}
        return true;
    }
    private boolean sourceGroup(long chat) {return chat==config.chat.chatId()||(config.advancementEnabled()&&chat==config.advancements.chatId());}
    private boolean admin(long chat,long user) throws Exception {return user>0&&Set.of("administrator","creator").contains(api.memberStatus(chat,user));}
    private void command(TelegramApi.Incoming update) throws Exception {
        String[] parts=update.text().trim().split("\\s+",2);String command=parts[0].split("@",2)[0].toLowerCase(Locale.ROOT),args=parts.length==2?parts[1].trim():"";
        if(update.anonymous()||update.userId()<=0) {notice(update,"Используйте личный профиль Telegram, а не анонимное имя группы.");return;}
        if(!command.equals("/report")&&!admin(update.chatId(),update.userId())) {notice(update,"Команда доступна только действующим администраторам этой группы.");return;}
        if(command.equals("/modhelp")) {notice(update,"Ответом на сообщение: /report причина; для администраторов: /mute 10m, /unmute, /ban [1d], /unban, /warn причина, /warnings, /unwarn, /clearwarns. Сроки: m — минуты, h — часы, d — дни; /ban без срока — навсегда.");return;}
        var target=update.reply();
        if(target==null||target.userId()<=0||target.bot()) {notice(update,"Выберите сообщение пользователя → Ответить → "+command+". Сообщения каналов и ботов не поддерживаются.");return;}
        if(command.equals("/report")) {report(update,target,args);return;}
        if(!command.equals("/warnings")&&admin(update.chatId(),target.userId())) {notice(update,"Нельзя применять модерацию к администратору группы.");return;}
        String result;
        switch(command) {
            case "/mute" -> {long seconds=duration(args,false);api.muteMember(update.chatId(),target.userId(),until(seconds),true);result="Мут: "+args;}
            case "/unmute" -> {api.muteMember(update.chatId(),target.userId(),0,false);result="Мут снят.";}
            case "/ban" -> {long seconds=duration(args,true);api.banMember(update.chatId(),target.userId(),until(seconds));result="Бан: "+(seconds==0?"навсегда":args);}
            case "/unban" -> {api.unbanMember(update.chatId(),target.userId());result="Бан снят.";}
            case "/warn" -> result=warn(update.chatId(),target.userId(),args.isBlank()?"Без причины":args);
            case "/warnings" -> result="Предупреждений: "+warnings(update.chatId(),target.userId());
            case "/unwarn" -> {execute("DELETE FROM warnings WHERE id=(SELECT MAX(id) FROM warnings WHERE chat=? AND target=?)",update.chatId(),target.userId());result="Предупреждений осталось: "+warnings(update.chatId(),target.userId());}
            case "/clearwarns" -> {execute("DELETE FROM warnings WHERE chat=? AND target=?",update.chatId(),target.userId());result="Предупреждения очищены.";}
            default -> {return;}
        }
        notice(update,target.name()+": "+result);
    }
    static long duration(String text,boolean allowForever) {
        if(allowForever&&(text.isBlank()||text.equals("0"))) return 0;
        if(!text.matches("[1-9][0-9]{0,5}[mhd]")) throw new IllegalArgumentException("Срок: 10m, 2h, 7d (не более 365 дней)");
        long number=Long.parseLong(text.substring(0,text.length()-1));long seconds=number*switch(text.charAt(text.length()-1)){case 'm'->60;case 'h'->3600;default->86400;};
        if(seconds>365L*86400) throw new IllegalArgumentException("Срок не более 365 дней");return seconds;
    }
    private static long until(long seconds) {return seconds==0?0:System.currentTimeMillis()/1000+seconds;}
    private int maxWarnings() {return Math.max(1,Math.min(100,config.yaml.getInt("reports.maxWarnings",5)));}
    private String warn(long chat,long target,String reason) throws Exception {
        execute("INSERT INTO warnings(chat,target,reason) VALUES(?,?,?)",chat,target,cut(reason,1000));int count=warnings(chat,target);
        if(count>=maxWarnings()&&config.flag("reports.autoBan",true)) {
            try {api.banMember(chat,target,until(86400));return "Предупреждение "+count+"/"+maxWarnings()+". Бан на 1 день.";}
            catch(Exception failure) {log.warning("Автобан после предупреждения не подтверждён: "+api.safe(failure));return "Предупреждение "+count+"/"+maxWarnings()+" сохранено. Автобан не подтверждён: проверьте права бота и состояние участника.";}
        }
        return "Предупреждение "+count+"/"+maxWarnings()+".";
    }
    private int warnings(long chat,long target) throws Exception {try(var s=db.prepareStatement("SELECT COUNT(*) FROM warnings WHERE chat=? AND target=?")){s.setLong(1,chat);s.setLong(2,target);try(var r=s.executeQuery()){r.next();return r.getInt(1);}}}
    private void report(TelegramApi.Incoming update,TelegramApi.Reply target,String reason) throws Exception {
        String key=update.chatId()+":"+update.userId();long now=System.currentTimeMillis();
        if(now-cooldown.getOrDefault(key,0L)<30000) {notice(update,"Подождите 30 секунд перед следующим репортом.");return;}
        if(cooldown.size()>10000) cooldown.entrySet().removeIf(e->now-e.getValue()>60000);
        cooldown.put(key,now);
        String id=UUID.randomUUID().toString().replace("-","");
        var report=new Report(id,update.chatId(),update.topicId(),target.messageId(),target.userId(),cut(target.name(),120),cut(target.text(),1200),reason.isBlank()?"Не указана":cut(reason,400),cut(update.displayName(),120),0);
        execute("INSERT INTO reports VALUES(?,?,?)",id,gson.toJson(report),"sending");
        int sent=api.sendHtml(config.reports.chatId(),config.reports.topicId(),reportText(report),false,buttons(report));
        report=new Report(id,report.chat(),report.topic(),report.sourceMessage(),report.target(),report.name(),report.text(),report.reason(),report.reporter(),sent);
        execute("UPDATE reports SET payload=?,state='open' WHERE id=?",gson.toJson(report),id);
        notice(update,"Репорт отправлен администраторам.");
    }
    private String reportText(Report r) {
        String link=r.chat()< -1000000000000L?"\n<a href=\"https://t.me/c/"+Long.toString(r.chat()).substring(4)+"/"+r.sourceMessage()+"\">Открыть сообщение</a>":"";
        return "🚨 <b>Репорт</b>\nПользователь: "+esc(r.name())+"\nОтправитель: "+esc(r.reporter())+"\nПричина: "+esc(r.reason())+"\n\n"+esc(r.text())+link;
    }
    private List<TelegramCommands.Button> buttons(Report r) {return List.of(button("🔇 Мут",r,"mute",0),button("🔨 Бан",r,"ban",0),button("⚠️ Предупреждение",r,"warn",1),button("Закрыть без наказания",r,"ignore",2));}
    private TelegramCommands.Button button(String label,Report r,String op,int row) {return new TelegramCommands.Button(label,"vtr:"+r.id()+":"+op,row);}
    private void callback(TelegramApi.Incoming update) throws Exception {
        String[] parts=update.callbackData().split(":",3);if(parts.length!=3) return;
        Report report;String state;
        try(var s=db.prepareStatement("SELECT payload,state FROM reports WHERE id=?")){s.setString(1,parts[1]);try(var rs=s.executeQuery()){if(!rs.next()){api.answerCallback(update.callbackId(),"Репорт недоступен.",true);return;}report=gson.fromJson(rs.getString(1),Report.class);state=rs.getString(2);}}
        if(report.reportMessage()!=update.messageId()||!sourceGroup(report.chat())||!config.reports.matches(update)) {api.answerCallback(update.callbackId(),"Кнопка недоступна.",true);return;}
        if(!admin(report.chat(),update.userId())) {api.answerCallback(update.callbackId(),"Нужны действующие права администратора исходной группы.",true);return;}
        if(!state.equals("open")) {api.answerCallback(update.callbackId(),"Репорт уже обработан. Повторное действие не выполнено.",true);return;}
        String op=parts[2];
        if(op.equals("back")) {api.editHtml(update.chatId(),update.messageId(),reportText(report),buttons(report));api.answerCallback(update.callbackId(),"",false);return;}
        if(op.equals("mute")||op.equals("ban")) {
            long[] seconds=op.equals("mute")?new long[]{600,1800,3600,21600,86400,0}:new long[]{3600,86400,604800,2592000,0};List<TelegramCommands.Button> keys=new ArrayList<>();
            for(int i=0;i<seconds.length;i++){long value=seconds[i];String label=value==0?"Навсегда":value<3600?value/60+" мин":value<86400?value/3600+" ч":value/86400+" д";keys.add(button(label,report,op+"_"+value,i/2));}
            keys.add(button("↩ Назад",report,"back",4));api.editHtml(update.chatId(),update.messageId(),reportText(report)+"\n\nВыберите срок "+(op.equals("mute")?"мута":"бана"),keys);api.answerCallback(update.callbackId(),"",false);return;
        }
        if(!op.equals("ignore")&&admin(report.chat(),report.target())) {api.answerCallback(update.callbackId(),"Пользователь — администратор. Наказание запрещено.",true);return;}
        boolean mute=op.startsWith("mute_"),ban=op.startsWith("ban_");long seconds=0;
        if(mute||ban) {try {seconds=Long.parseLong(op.substring(op.indexOf('_')+1));}catch(NumberFormatException bad){return;}if(!(mute?Set.of(0L,600L,1800L,3600L,21600L,86400L):Set.of(0L,3600L,86400L,604800L,2592000L)).contains(seconds)) return;}
        else if(!Set.of("warn","ignore").contains(op)) return;
        // Claim before API effects: an interrupted request cannot replay a warning or punishment.
        execute("UPDATE reports SET state='processing' WHERE id=?",report.id());
        String result;
        try {
            if(mute){api.muteMember(report.chat(),report.target(),until(seconds),true);result="Мут выдан.";}
            else if(ban){api.banMember(report.chat(),report.target(),until(seconds));result="Бан выдан.";}
            else if(op.equals("warn")) result=warn(report.chat(),report.target(),report.reason());
            else result="Закрыт без наказания.";
            execute("UPDATE reports SET state='closed' WHERE id=?",report.id());
        } catch(Exception failure) {execute("UPDATE reports SET state='failed' WHERE id=?",report.id());throw failure;}
        api.editHtml(update.chatId(),update.messageId(),reportText(report)+"\n\n✅ "+esc(result),List.of());api.answerCallback(update.callbackId(),result,false);
    }
    private void notice(TelegramApi.Incoming update,String text) throws Exception {int id=api.sendHtml(update.chatId(),update.topicId(),esc(text),true);expiry.track(update.chatId(),id,System.currentTimeMillis()+30000);}
    private static String esc(String s) {return TelegramChatFormat.escape(s);}
    private static String cut(String value,int length) {return value==null?"":value.substring(0,Math.min(value.length(),length));}
    private void execute(String sql,Object... args) throws Exception {try(var s=db.prepareStatement(sql)){for(int i=0;i<args.length;i++)s.setObject(i+1,args[i]);s.executeUpdate();}}
    @Override public void close() {
        closed=true;worker.getQueue().clear();
        try {worker.execute(()->{try{db.close();}catch(SQLException ignored){}});}catch(RejectedExecutionException ignored){}
        worker.shutdown();
        try {worker.awaitTermination(2,TimeUnit.SECONDS);}catch(InterruptedException stopped){Thread.currentThread().interrupt();}
    }
}
